apiVersion: v1
kind: Secret
metadata:
  name: ee-factory-secrets
  namespace: ee-factory-lab
type: Opaque
stringData:
  postgres-password: replace-me
  database-url: postgresql://ee_factory:replace-me@postgres:5432/ee_factory
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-docker-config
  namespace: ee-factory-lab
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "username": "replace-me",
          "password": "replace-me",
          "auth": "cmVwbGFjZS1tZTpyZXBsYWNlLW1l"
        }
      }
    }
